steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - helloworld
  - --region=asia-northeast1
  - --source=.
  - --trigger-http
  - --runtime=go119
